---
kind: pipeline
type: docker
name: Default

trigger:
  event: [push, tag]

image_pull_secrets:
- pull_docker_config

steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags

- name: install-instantclient
  image: quay.io/tike/drone-install-instantclient:12.2

- name: test
  image: node:8
  commands:
    - export OCI_LIB_DIR=$PWD/instantclient
    - export OCI_INC_DIR=$PWD/instantclient/sdk/include
    - npm install
    - npm test

- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/tike/aleph-record-caretaker
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: secret
name: pull_docker_config
data:
---
kind: secret
name: docker_username
data: Nks0fG0sSsf0+l9eOqACPfINYzU7EZZW3/0iVzpcApptLcezK09WIE6zU5d/Kj1pzcbyDObWKf9D+l7DFJGvnw==
---
kind: secret
name: docker_password
data: Pcrq4zSPwZcjkYDsghGVjslN7+JF+jVfiYXJtzKnA+b+t0GYiQ/ti4SVW+LtkxtfOURnd7/bzPw51TBPqwzLguGGLnMPKn607BpBgSMb/3XwtRO5bi3Qw+1zf0U=
---
kind: signature
hmac: dd778764f21c005b8c3251336f87c029b716445177acc4f42ac12b1125ca0523

...
