
const TASK_TYPES = {
  FENAU_ASTERI: 'FENAU_ASTERI',
  LINKED_FENAU_ASTERI: 'LINKED_FENAU_ASTERI',
  FENNI_ASTERI: 'FENNI_ASTERI',
  MELINDA_ASTERI: 'MELINDA_ASTERI',
  ASTERI_ASTERI: 'ASTERI_ASTERI',
  LINKED_ASTERI_ASTERI: 'LINKED_ASTERI_ASTERI'
};


module.exports = {
  TASK_TYPES
};
